### ISSUE TITLE
node-echarts module exports

### ISSUE THREAD

**Issue by Sayen0** [suxiaoxin/node-echarts#16]
When I refer to 'import node_echarts from 'node-echarts'; '  it happens the following problem occurred:
C:\work\orgMonthy-pdf>babel-node index.js
C:\work\orgMonthy-pdf\node_modules\node-echarts\index.js:17
module.exports = async (config) => {
                       ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\123456\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:/work/orgMonthy-pdf/index.js:2:1)

**Comment by suxiaoxin** [comment]
nodejs version（>=7.6）
